### ISSUE TITLE
apt-update runtime warning

### ISSUE THREAD

**Issue by abhi1693** [PandaLinux/pandaOS#10]
`apt-update` or `apt-get update` throws the following warning at runtime:

```
No sandbox user '_apt' on the system, can not drop privileges
```

**Comment by abhi1693** [comment]
This bug has been fixed in `dpkg` branch. It will be merged to `master` in the next release.

**Comment by rajudev** [comment]
@abhi1693 I am experiencing the same bug. Could you enlighten me with the changes I can make to solve this issue?

**Comment by abhi1693** [comment]
@rajuvindane `sudo useradd -r -M --system _apt` should resolve your issue. I would suggest you to use [base-64](https://github.com/PandaLinux/base-64) as this repository is deprecated.

**Comment by kmchen13** [comment]
Hi,
After an upgrade to Debian Stretch I encounter that warning. Here is what I tried:
`
vm293 ~ > sudo useradd -r -M --system _apt
useradd: user '_apt' already exists
vm293 ~ >  grep _apt /etc/passwd /etc/shadow
/etc/passwd:_apt:x:120:65534::/nonexistent:/bin/false
/etc/shadow:_apt:*:18165:0:99999:7:::
`
Any advice apreciated

**Comment by abhi1693** [comment]
This repository is deprecated. I'm working on another repository at https://github.com/pandaLinux/base-64
